// Imports
import express from 'express';
import ratelimit from 'express-rate-limit';
import faker from 'faker';
import config from '../configuration.js';

// Instantiate router component
const router = express.Router();

// Generate a fake vehicle
const generateVehicle = () => {
  let vehicle = {
    Sold: Math.random() < 0.2,
    StockNum: Math.floor(Math.random() * 250) + 1,
    ModelYear: Math.floor(Math.random() * (2022 - 2017) + 2016),
    Make: "", /* Generated by Model */
    Model: faker.vehicle.vehicle(),
    Trim: "TRIM",
    Drivetrain: "AWD",
    Link: "",
    Price: parseInt(faker.commerce.price(15000, 45000, 0, "")),
    MSRP: parseInt(faker.commerce.price(16000, 50000, 0, "")),
    VIN: faker.vehicle.vin(),
    IntColor: [faker.vehicle.color()],
    ExtColor: [faker.vehicle.color()],
    Owners: Math.floor(Math.random() * 3) + 1,
    EPA: {
      "City": 26,
      "Highway": 32
    },
    Odometer: Math.floor(Math.random() * 100000),
    Images: [],
  };
  vehicle.Link = "/vehicles/" + `${vehicle.StockNum}-${vehicle.ModelYear}-${vehicle.Model.trim()}`.toLowerCase().replace(/\s/g, "-");

  return vehicle;
};

// Use RateLimit Module
router.use(new ratelimit({
  windowMs: 15 * 1000,
  max: 5
}));

/**
 * Root directory
 *
 * @author Alec M.
 */
router.get('/', async (request, response) => {
  // Send default response
  response.status(404).send("");
});

/**
 * Text search query for vehicles
 *
 * @author Alec M.
 * @date 2021-11-20 16:18:00
 */
router.get('/search/:query', async (request, response) => {
  // Generate fake response vehicles
  let vehicles = [];
  for (let i = 0; i < 5; i++) {
    vehicles.push(generateVehicle());
  }

  // Render respons
  response.render('partials/searchCardContainer', {
    config,
    vehicles
  });
});

// Export Router
export default router;
