// Imports
import express from 'express';
import faker from 'faker';
import config from '../configuration.js';

// Instantiate router component
const router = express.Router();

// Generate a fake vehicle
const generateVehicle = () => {
  let vehicle = {
    Sold: Math.random() < 0.2,
    StockNum: Math.floor(Math.random() * 250) + 1,
    ModelYear: Math.floor(Math.random() * (2022 - 2017) + 2016),
    Make: "", /* Generated by Model */
    Model: faker.vehicle.vehicle(),
    Trim: "TRIM",
    Drivetrain: "AWD",
    Link: "",
    Price: parseInt(faker.commerce.price(15000, 45000, 0, "")),
    MSRP: parseInt(faker.commerce.price(16000, 50000, 0, "")),
    VIN: faker.vehicle.vin(),
    IntColor: [faker.vehicle.color()],
    ExtColor: [faker.vehicle.color()],
    Owners: Math.floor(Math.random() * 3) + 1,
    EPA: {
      "City": 26,
      "Highway": 32
    },
    Odometer: Math.floor(Math.random() * 100000),
    Images: []
  };
  vehicle.Link = config.application.URL + "/vehicles/" + `${vehicle.StockNum}-${vehicle.ModelYear}-${vehicle.Model.trim()}`.toLowerCase().replace(/\s/g, "-");

  return vehicle;
};

/**
 * Root directory
 *
 * @author Alec M.
 */
router.get('/', async (request, response) => {
  // Generate fake response vehicles
  let vehicles = [];
  for (let i = 0; i <= 19; i++) {
    vehicles.push(generateVehicle());
  }

  // Send default response
  response.render('index', {
    config,
    context: {
      query: "All Vehicles"
    },
    vehicles
  });
});

router.get('/vehicles/:vehicle', async (request, response) => {
  // Generate recommendations
  let vehicles = [];
  for (let i = 0; i < 3; i++) {
    vehicles.push(generateVehicle());
  }

  // Send default response
  response.render('listing', {
    config,
    context: {
      query: "",
      queryLink: "/",
    },
    vehicle: generateVehicle(),
    recommendations: vehicles,
  });
});

// Export Router
export default router;
